### ISSUE TITLE
wiki pages documentation

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#12]
it will be a good idea to provide a list of documentation on how to use the gem on a different scenarios.

**Comment by tobithiel** [comment]
Can you be more specific what you think is not documented?
My impression is that our README covers the basic use cases quite well and the example project shows actual usage of Strongbolt (which also allows you to tinker with it).
Knowing a lot about Strongbolt my view can be fairly distorted though.

**Comment by ahmgeek** [comment]
I've already played quite enough with it, but something like the can? cannot methods are not documented.
Also, If I need to say something like `( user.user_groups.includes?("superadmin") )` to see if the user is in the super admins group, as I see the example puts a too long name in both the Roles table and the UserGroups table.
if I need to check the user_groups I guess I need to check the id or choose a small name ?
regardless the implementation and the rails features, what I meant is use cases or scenarios on how to check user's group etc..
if that's there by default, then I can't get it from the readme :(

**Comment by tobithiel** [comment]
I'll add documentation for the `can?`/`cannot?` and a few other public methods in the next few days.
We don't really have something to check if a user is in a group. It's just a normal rails association though, so `user.user_groups.where(name: 'my group').exists?` will do.
I'll add some documentation on which associations are added to external models, so that this is more clear.

**Comment by ahmgeek** [comment]
:heart:

**Comment by tobithiel** [comment]
The readme should now have documentation on all publically exposed methods and associations.

**Comment by ahmgeek** [comment]
thanks man.
