### ISSUE TITLE
Using tenants

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#14]
Sorry for the continuous bothering, How can I use the tenants ?
say I have an organization model, school model and users. I add a role for the Organization admin, school admin. so I want say an organization admin see only the schools he made, and the school admin to see only the school's data he assigned to by the organization admin.
By using tenants I add the User, School, Organization the tenants configuration in strong bolt config.
but after that, what should I do ?

**Comment by tobithiel** [comment]
As far as I got what you're saying, you configured `config.tenants = 'User', 'School', 'Organization'`. It doesn't make sense to use `User` as a tenant, since you don't want to assign users to users most probably, I think.
Anyways, every tenant will automatically be setup by creating an association with your user class. So you can assign users to organization or schools, by doing for example `user.schools << School.find_by(name: 'My School Name')`. Strongbolt interprets that as you giving the user access to that school.
Let's say you have rooms which belong to schools. If one of your Roles is like this:
- Model: Room
- Require Ownership? No
- Require Tenant Access? **Yes**
- Actions: Find
Each user who is assigned that role, will only be able to view rooms which belong to the schools he was assigned to.
Strongbolt figures the relationship between a room and school out based on the ActiveRecord associations you've set up between them. A room would have an attribute `school_id` in that scenario with an ActiveRecord association setup on the model. Strongbolt finds that and checks if `room.school_id` is in `user.schools` basically. If yes => great the user will get the model and everything is normal. If no => an unautorized exception will be thrown.

Check out [our example app](https://github.com/AnalyticsMediaGroup/strongbolt_example), which is great to play around with the tenant rules, I think. If you assign or remove users to categories, you'll see how they can access new articles or can't access articles anymore, they were able to previously.

**Comment by ahmgeek** [comment]
Let's say a User could be an admin for a school via roles.
and a User could retrieve all the users - could be `studesnts`, `teachers`- whom in that school.
So a User should have access to the User tenants too ?
to be able to find those whom in that school ?
or what a proper approach to achieve this ?

**Comment by tobithiel** [comment]
I think something like this would work. Obviously test that it behaves like you want before using it.
```ruby
config.tenants = 'School'

class School <  ActiveRecord::Base
  has_many :users
end
class User <  ActiveRecord::Base
  # implicitly added by Strongbolt
  has_many :schools
end
```
Capability 1:
- Role: School Admin
- Model: User
- Require Ownership? No
- Require Tenant Access? Yes 
- Actions: Create, Find, Update, Delete
- Comment: Can find any user and can do everything with them.

Capability 2:
- Role: Teacher
- Model: User
- Require Ownership? No
- Require Tenant Access? Yes 
- Actions: Find
- Comment: Can find any user, but not modify

Capability 3:
- Role: Student
- Model: User
- Require Ownership? Yes
- Require Tenant Access? No 
- Actions: Find, Update
- Comment: Can only find himself and update himself

You assign users to schools through the tenant relationship that is set up for you and then based on the roles of the user, it is either Admin, Teacher or Student.
This way the roles can't be mixed, you'll probably have to use different user accounts for that I think. You'll have to figure out how the organization ties into that, I don't get the semantics there.

I'd try to only use one Tenant, I think it's a lot easier to think and reason about. Strongbolt should work fine with more though.

**Comment by ahmgeek** [comment]
Thanks man for your help, I didn't get the usage of : `Require Ownership? Yes` & `Require Tenant Access? No`
what is the purpose of each of them regards the roles, as I see the `student` don't need require a tenant access but require an ownership.

**Comment by tobithiel** [comment]
Require ownership:
Model needs an attribute `user_id` which is the users id. If it's the User model, it just looks at `id` attribute. So a user with ID 3 could only access the User with id = 3 (himself) in the example above.

Require Tenant Access:
Model needs a relationship to the tenant class. In the example above that's the `has_may :schools` relationship.

Example:
User A can access (returned by `userA.schools`):
- School A

User B can access (returned by `userB.schools`):
- School A
- School B

User A has role `Student`, User B has role `Teacher`. User A can only access himself (as explained above). User B can access every user in School A & B (Tenant Access).

This is a horrible example to explain this on, because the user-tenant and tenant-model associations are basically the same. It should be much clearer on our example app, where the user-tenant and tenant-model associations are different.

**Comment by ahmgeek** [comment]
:smile: I read the example code and got it clearly, but in my case it's like you've just said, a horrible example.
but you've said enough, by the time when I finish the requirements, will write about it, it may help others whom want to implement Strongbolt in complex apps.
thanks for your help Tobias.
