### ISSUE TITLE
A question regard controller overriding

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#17]
I am overriding this controller `Strongbolt::UserGroup,` in my ActiveAdmin, the reason is because I want to override the whole strongbolt views experience, the issue is I want to add an autocomplete action to get the users whom assigned to groups, the issue is [here](https://github.com/AnalyticsMediaGroup/strongbolt/blob/master/lib/strongbolt/bolted_controller.rb#L7-L14)  I guess

I git the error
```
AbstractController::ActionNotFound (The action 'autocomplete' could not be found for Strongbolt::UserGroupsController):
```
when I add this to the routes: 
` get 'autocomplete_user' => 'strongbolt/user_groups#autocomplete'`
so, anyway to bypass this ?

**Comment by tobithiel** [comment]
You can just override the view provided by Strongbolt, by having your own view in `app/views/strongbolt/user_groups/...`. You'll probably have a `UsersController` or something like that that you can query for the users or something like that.
That's how we do it internally. Since the user class isn't provided by Strongbolt, we don't bundle things like that.
Overriding controllers isn't really supported from our end. You can monkey patch the controller to include that action though I guess. Or just reimplement the controller under a different name and don't use the provided controller.
