### ISSUE TITLE
Tenant usage to return ActiveRecord::Rela

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#20]
The usage example noted that to return from tenant `current_user.accessible_categories.map(&:articles).flatten.uniq`.
Lots of time the return type conflicts with something like activeadmin or administrations gems in a thing that the rendering is automatically generated, so it needs an `ActiveRecord::Relation` instead of `Array`.
I used something like: `User.where(id: current_user.accessible_organizations.map(&:schools).flatten.uniq.map(&:users).flatten.uniq)`
but it's a really bad way in such a thing as it adds more complexity,  I am still searching for a way to return an activerecord relation instead of an array, but as you used it internally, I guess you stumbled in such a case, so any hints ?

**Comment by tobithiel** [comment]
I'm not really sure I understand what you're saying, but I think you're looking for something like this: `Article.where(category: current_user.accessible_categories)`

**Comment by ahmgeek** [comment]
isn't that adding more complexity by looping over the ids I've already got to return there activerecord relation ? 
wouldn't it be great to return the activerecord relation + the  array of objects ? 
I mean adding more options adds more value ?

**Comment by tobithiel** [comment]
As I said, I don't really get the issue you're having. Where should this be added? This is all happening outside of Strongbolt.
This should create a SQL query along the lines of `SELECT * FROM articles WHERE category_id IN (1, 2, ...)`, which is more efficient than the previous solution since the articles aren't retrieved for each category individually (since `map` just iterates over all categories and then runs `SELECT * FROM articles WHERE category_id = 1`).
