### ISSUE TITLE
HABTM Tables issue - 

### ISSUE THREAD

**Issue by chriskwss** [AnalyticsMediaGroup/strongbolt#26]
Bolting an existing application with Tenant model. 

config.tenants = "School"

Students model is defined with
```
class Student < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :schools
```

In strongbolt.rb I have the following configured: 
```
config.models = 'User', 'School', 'Student',  'Subject',
... 
'Student::HABTM_Users', 'School::HABTM_Students', 'School::HABTM_Users', 'Subject::HABTM_Users'
```
When attempting to add a new Student via 

```
  def create
    if current_user.can?(:create, Strongbolt::Role)
      logger.debug "**** Student::HABTM_Users.owned #{Student::HABTM_Users.owned?}"
      logger.debug "**** Student::HABTM_Users.owner_attribute #{Student::HABTM_Users.owner_attribute}"
      logger.debug "**** current_user.capabilities #{current_user.capabilities}"
      logger.debug "**** current_user.can?(:create, Student::HABTM_Users) #{current_user.can?(:create, Student::HABTM_Users)}"
      @student = Student.new(student_params)
<snip>
```

I get the following error: 
**Strongbolt::Unauthorized in StudentsController#create
create permission not granted to User:1 for resource HABTM_Users:**

But the user I'm using should be able to access Student::HABTM_Users -- from the debug output: 

```
**** Student::HABTM_Users.owned true
**** Student::HABTM_Users.owner_attribute user_id
**** current_user.capabilities [#<Strongbolt::Capability id: 1, name: nil, description: nil, model: "AccRecord", action: "find", attr: nil, require_ownership: false, require_tenant_access: false,
<snip>
#<Strongbolt::Capability id: 86, name: nil, description: nil, model: "Student::HABTM_Users", action: "create", attr: nil, require_ownership: false, require_tenant_access: false, created_at: "2016-12-12 02:55:44", updated_at: "2016-12-12 02:55:44">,
<snip>
Authorizing user to perform create on Student::HABTM_Users(student_id: integer, user_id: integer)
**** current_user.can?(:create, Student::HABTM_Users) false
<snip>
Authorizing user to perform create on #<Student::HABTM_Users student_id: 33, user_id: 1>
Populating tenants cache for user 1
Authorizing user to perform find on School(id: integer, school_name: string, school_street: string, school_state: string, school_zip: string, school_phone: string, school_contact_name: string, created_at: datetime, updated_at: datetime, school_city: string)
   (0.3ms)  SELECT `schools`.`id` FROM `schools`
2 School
   (1.1ms)  ROLLBACK
Completed 500 Internal Server Error in 57ms (ActiveRecord: 6.0ms)

Strongbolt::Unauthorized (create permission not granted to User:1 for resource HABTM_Users:):
```

I see where there is 
**#<Strongbolt::Capability id: 86, name: nil, description: nil, model: "Student::HABTM_Users", action: "create", attr: nil, require_ownership: false, require_tenant_access: false, created_at: "2016-12-12 02:55:44", updated_at: "2016-12-12 02:55:44">**

It looks like any HABTM associations are being missed?

**Comment by chriskwss** [comment]
I just noticed that 
```
logger.debug "**** Student::HABTM_Users.name_for_authorization #{Student::HABTM_Users.name_for_authorization}"
```
Returns 'HABTM_Users' instead of a proper model name like Students/Users

I assume this could be worked around with a has_many :through, but want to verify behavior here.

**Comment by tobithiel** [comment]
Yeah, `has_and_belongs_to_many` associations don't really work right now. They are a bit difficult to work with, because there is no explicit join model class. ActiveRecord creates one for each side individually (so you end up with two) and you usually have to grant access to both. That's why we started preferring `has_many ..., through: ...`, where the join model class is explicit.

The bug you're experiencing is due to the fact, that the implicit join model class strips the namespace from its name. It should be `Student::HABTM_Users` and not `HABTM_Users`. You can see this by calling `Student::HABTM_Users.name => "HABTM_Users"`, whereas normally any class would return `Student::HABTM_Users.name => "Student::HABTM_Users"`.

My quick & dirty workaround to get it working was to do something like this:
```ruby
class Student::HABTM_Users
  def self.name
    "Student::HABTM_Users"
  end
end
```

Let me know if that helps in your situation as well.
That's obviously not a long-term solution, but I'm not sure yet if Strongbolt should work around this edge case or if we should open an issue with ActiveRecord, that they should return the correct name (Technically these implicit join model classes are private and shouldn't be accessed from the outside as far as I am aware).

**Comment by tobithiel** [comment]
I'm gonna close this, please reopen it, if the issue persists.
